# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/monoctl
    ldflags:
      - -X=github.com/finleap-connect/monoctl/internal/version.Version={{.Version}}
      - -X=github.com/finleap-connect/monoctl/internal/version.Commit={{.Version}}
archives:
  - replacements:
      darwin: osx
      windows: win
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: monoctl
    description: CLI for Monoskope. AuthN & AuthZ for Kubernetes multi-cluster, multi-cloud environments.
    homepage: https://github.com/finleap-connect/monoctl
    license: "Apache"
    tap:
      owner: finleap-connect
      name: homebrew-monoctl
    skip_upload: auto
