name: Draft Release

on:
  push:
    branches: [ main ]
    tags: [ '!*' ]
  pull_request:
    branches: [ main ]
      
jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Update draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}