name: goreleaser

on:
  push:
    tags: ["v*"]

env:
  GO_VERSION: ">=1.19.2"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: build
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_REPO_WRITE }}
      - uses: actions/upload-artifact@v3
        with:
          name: monoctl-binaries
          path: ./monoctl-*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set VERSION
        run: echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Publish draft
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          version: ${{ env.VERSION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-artifacts:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download monoctl binaries
        uses: actions/download-artifact@v3
        with:
          name: monoctl-binaries
      - name: Upload Release Artifacts
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./monoctl-*"]'